### ISSUE TITLE
elements.geom.GeomNode.getReferenceY returns odd results with certain angles

### ISSUE THREAD

**Issue by BSoDium** [BSoDium/Spinel#4]
The following method seems to behave in a strange way with certain rotation values : 
https://github.com/l3alr0g/Spinel/blob/c256fa9b31e226b7b2f7e0fb6a1bb6911735d165/src/main/java/io/github/spinel/elements/geom/GeomNode.java#L148-L152

Expected behaviour : should return the tangent vector e_phi, phi being the pitch angle.

**Comment by l3alr0g** [comment]
Actually, getReferenceZ seems odd too
